// THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY.

package nintaco

// API provides programmatic control of the emulator at a very granular level.
type API interface {
	AcknowledgeInterrupt()
	AddAccessPointListener(listener AccessPointListener, accessPointType, address int)
	AddAccessPointListener2(listener AccessPointListener, accessPointType, minAddress, maxAddress int)
	AddAccessPointListener3(listener AccessPointListener, accessPointType, minAddress, maxAddress, bank int)
	AddActivateListener(listener ActivateListener)
	AddCheat(address, value, compare int, description string, enabled bool)
	AddControllersListener(listener ControllersListener)
	AddDeactivateListener(listener DeactivateListener)
	AddFrameListener(listener FrameListener)
	AddGameGenie(gameGenieCode, description string, enabled bool)
	AddProActionRocky(proActionRockyCode, description string, enabled bool)
	AddScanlineCycleListener(listener ScanlineCycleListener, scanline, scanlineCycle int)
	AddScanlineListener(listener ScanlineListener, scanline int)
	AddSpriteZeroListener(listener SpriteZeroListener)
	AddStatusListener(listener StatusListener)
	AddStopListener(listener StopListener)
	ClipRect(x, y, width, height int)
	Close()
	CopyArea(x, y, width, height, dx, dy int)
	CreateSprite(id, width, height int, pixels []int)
	DeleteSprite(id int)
	Draw3DRect(x, y, width, height int, raised bool)
	DrawArc(x, y, width, height, startAngle, arcAngle int)
	DrawChar(c rune, x, y int)
	DrawChars(chars []rune, offset, length, x, y int, monospaced bool)
	DrawLine(x1, y1, x2, y2 int)
	DrawOval(x, y, width, height int)
	DrawPolygon(xPoints, yPoints []int, nPoints int)
	DrawPolyline(xPoints, yPoints []int, nPoints int)
	DrawRect(x, y, width, height int)
	DrawRoundRect(x, y, width, height, arcWidth, arcHeight int)
	DrawSprite(id, x, y int)
	DrawString(str string, x, y int, monospaced bool)
	EjectDisk()
	Fill3DRect(x, y, width, height int, raised bool)
	FillArc(x, y, width, height, startAngle, arcAngle int)
	FillOval(x, y, width, height int)
	FillPolygon(xPoints, yPoints []int, nPoints int)
	FillRect(x, y, width, height int)
	FillRoundRect(x, y, width, height, arcWidth, arcHeight int)
	FlipDiskSide()
	GetA() int
	GetArchiveEntries(archiveFileName string) []string
	GetCameraX() int
	GetCameraY() int
	GetCharsWidth(chars []rune, monospaced bool) int
	GetChrRomSize() int
	GetColor() int
	GetContentDirectory() string
	GetDefaultArchiveEntry(archiveFileName string) string
	GetDiskSides() int
	GetDot() int
	GetFileInfo() string
	GetFrameCount() int
	GetP() int
	GetPC() int
	GetPPUt() int
	GetPPUv() int
	GetPPUx() int
	GetPixel(x, y int) int
	GetPixels(pixels []int)
	GetPrgRomSize() int
	GetS() int
	GetScanline() int
	GetScanlineCount() int
	GetStringWidth(str string, monospaced bool) int
	GetTVSystem() string
	GetWorkingDirectory() string
	GetX() int
	GetY() int
	GetZapperX() int
	GetZapperY() int
	Glitch()
	InsertCoin()
	InsertDisk(disk, side int)
	IsC() bool
	IsD() bool
	IsI() bool
	IsN() bool
	IsPPUw() bool
	IsPaused() bool
	IsSpriteZeroHit() bool
	IsV() bool
	IsZ() bool
	IsZapperTrigger() bool
	LoadState(stateFileName string)
	Open(fileName string)
	OpenArchiveEntry(archiveFileName, entryFileName string)
	OpenDefaultArchiveEntry(archiveFileName string)
	PeekCPU(address int) int
	PeekCPU16(address int) int
	PeekCPU32(address int) int
	PowerCycle()
	PressServiceButton()
	QuickLoadState(slot int)
	QuickSaveState(slot int)
	ReadCPU(address int) int
	ReadCPU16(address int) int
	ReadCPU32(address int) int
	ReadChrRom(index int) int
	ReadGamepad(gamepad, button int) bool
	ReadOAM(address int) int
	ReadPPU(address int) int
	ReadPaletteRAM(address int) int
	ReadPrgRom(index int) int
	RemoveAccessPointListener(listener AccessPointListener)
	RemoveActivateListener(listener ActivateListener)
	RemoveCheat(address, value, compare int)
	RemoveControllersListener(listener ControllersListener)
	RemoveDeactivateListener(listener DeactivateListener)
	RemoveFrameListener(listener FrameListener)
	RemoveGameGenie(gameGenieCode string)
	RemoveProActionRocky(proActionRockyCode string)
	RemoveScanlineCycleListener(listener ScanlineCycleListener)
	RemoveScanlineListener(listener ScanlineListener)
	RemoveSpriteZeroListener(listener SpriteZeroListener)
	RemoveStatusListener(listener StatusListener)
	RemoveStopListener(listener StopListener)
	RequestInterrupt()
	Reset()
	ResetClip()
	Run()
	SaveScreenshot()
	SaveState(stateFileName string)
	ScreamIntoMicrophone()
	SetA(A int)
	SetC(C bool)
	SetCameraX(cameraX int)
	SetCameraY(cameraY int)
	SetClip(x, y, width, height int)
	SetColor(color int)
	SetD(D bool)
	SetFullscreenMode(fullscreenMode bool)
	SetI(I bool)
	SetN(N bool)
	SetP(P int)
	SetPC(PC int)
	SetPPUt(t int)
	SetPPUv(v int)
	SetPPUw(w bool)
	SetPPUx(x int)
	SetPaused(paused bool)
	SetPixel(x, y, color int)
	SetS(S int)
	SetSpeed(percent int)
	SetSpriteZeroHit(spriteZeroHit bool)
	SetTVSystem(tvSystem string)
	SetV(V bool)
	SetX(X int)
	SetY(Y int)
	SetZ(Z bool)
	SetZapperTrigger(zapperTrigger bool)
	SetZapperX(x int)
	SetZapperY(y int)
	ShowMessage(message string)
	StepToNextFrame()
	WriteCPU(address, value int)
	WriteCPU16(address, value int)
	WriteCPU32(address, value int)
	WriteChrRom(index, value int)
	WriteGamepad(gamepad, button int, value bool)
	WriteOAM(address, value int)
	WritePPU(address, value int)
	WritePaletteRAM(address, value int)
	WritePrgRom(index, value int)
}
